/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spike_netty_JavaNative */

#ifndef _Included_com_spike_netty_JavaNative
#define _Included_com_spike_netty_JavaNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spike_netty_JavaNative
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_spike_netty_JavaNative_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
